name: work_env_basemap
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - basemap=1.2.0
  - cartopy=0.17.0
  - certifi=2019.9.11=py36_0
  - cftime=1.0.3.4
  - cryptography=2.7
  - geographiclib=1.49
  - geopy=1.20.0
  - geos=3.6.2
  - matplotlib=3.1.1
  - metpy=0.10.0
  - netcdf4=1.4.2
  - netcdftime=1.0.0
  - numpy=1.16.4
  - pandas=0.24.2
  - pint=0.9
  - siphon
  - seaborn
  - xarray=0.12.1
